### ISSUE TITLE
Use of SentryBreadcrumbJsonProcessor before declaration in _config.py

### ISSUE THREAD

**Issue by seamonstr** [TeoZosa/structlog-sentry-logger#613] opened 2022-08-28 10:30 UTC
Hesitating to create this issue because I can't quite believe that nobody else has had this issue yet.  

Importing structlog-sentry-logger was segfaulting in MacOS with STRUCTLOG_SENTRY_LOGGER_CLOUD_SENTRY_INTEGRATION_MODE_ON declared, but not without it.

I eventually installed structlog-sentry-logger editable so that I could find out what was going on, and sure. enough: 
```
Traceback (most recent call last):
  File "/Users/simon.woodward/Code/nh-api/test.py", line 4, in <module>
    import structlog_sentry_logger
  File "/Users/simon.woodward/Code/structlog-sentry-logger/structlog_sentry_logger/__init__.py", line 5, in <module>
    from structlog_sentry_logger._config import (
  File "/Users/simon.woodward/Code/structlog-sentry-logger/structlog_sentry_logger/_config.py", line 413, in <module>
    __LOGGER = __get_meta_logger()
  File "/Users/simon.woodward/Code/structlog-sentry-logger/structlog_sentry_logger/_config.py", line 407, in __get_meta_logger
    set_optimized_structlog_config()
  File "/Users/simon.woodward/Code/structlog-sentry-logger/structlog_sentry_logger/_config.py", line 318, in set_optimized_structlog_config
    SentryBreadcrumbJsonProcessor(level=logging.ERROR, tag_keys="__all__")
NameError: name 'SentryBreadcrumbJsonProcessor' is not defined
```

I moved the declaration up the file, and bingo - all works.  Have I just missed something really obvious, or is this actually an issue..?

**Comment by TeoZosa** [comment] 2022-08-29 23:26
Hey @seamonstr, thanks for raising this issue! 

>  Have I just missed something really obvious, or is this actually an issue..?

You didn't miss anything, but the test suite did. This is definitely a bug that I was able to reproduce on my end. 

If you'd like, feel free to submit your fix in a PR. Once that's merged I can cut a new release. What do you think?

**Comment by TeoZosa** [comment] 2022-08-31 03:14
@seamonstr P.S. no obligation on the PR. I just wanted to give you the credit since you did all the legwork 😄 

Otherwise, I can make one from e9315d9 and get it into `master` ASAP.  Just let me know what you'd prefer.

**Closed** 2022-09-02 00:15 UTC

**Comment by seamonstr** [comment] 2022-09-02 07:52
Hey Teo - thanks for the fix! 

Sorry for the radio silence; I only actually get to do code on Fridays, so haven't responded before now. 🙂

S
